version: '3.8'

services:
    neo4j:
        image: neo4j:latest
        container_name: neo4j
        ports:
            - "7474:7474"  # HTTP interface
            - "7687:7687"  # Bolt protocol
        environment:
            NEO4J_AUTH: neo4j/test  # Username and password
        volumes:
            - ./data:/data  # Persistent data storage
            - ./import:/import  # Directory for dump file
